-- 019_is_admin_rpc.sql
-- ⚠️ ESTE ARQUIVO NÃO É MAIS NECESSÁRIO
-- A função is_admin_email foi removida do código do app.
-- NÃO execute este SQL. Mantenho apenas como referência.
-- Se já executou e deu erro, ignore — não afeta o funcionamento.
